name: Deploy

on:
  push:
    branches:
      - main
jobs:
  custom-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Heroku login credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login miprio101@gmail.com
              password ${{secrets.HEROKU_API_KEY}}
            machine git.heroku.com
              login miprio101@gmail.com
              password ${{secrets.HEROKU_API_KEY}}
          EOF
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_EMAIL: miprio101@gmail.com
      - name: Add Heroku remote
        run: heroku git:remote --app basemaxrubytest
        env:
          HEROKU_APP_NAME: basemaxrubytest
      - name: Push to Heroku
        run: git push heroku main